package car;

import util.Errors;
import util.Net;

import java.io.IOException;
import java.net.InetSocketAddress;

import static util.IO.*;

public class Main {
    public static final String TARGET_IP   = "192.168.1.21"; // TODO detect via broadcast?
    public static final int    TARGET_PORT = 5678;           // TODO move to config?

    public static void main(String[] args) throws IOException {
        Net.DEBUG = true;

        println("Started. Type 'q' or 'quit' to quit.");

        // UDP server
        Net.Server s = Net.listen(
                TARGET_PORT,
                (from, bytes) -> {
                    if (bytes.length != 3) {
                        println("! Got invalid packet: " + Net.toString(bytes));
                    } else {
                        byte id       = bytes[0];
                        byte steering = bytes[1];
                        byte speed    = bytes[2];

                        send_pong(from, id);
                    }
                });

        // command line interface
        for (String line : lines(System.in)) {
            if ("quit".equals(line) || "q".equals(line)) {
                System.out.println("Quiting.");
                s.close();
                return;
            } else {
                println(line);
            }
        }
    }

    /**
     * @param id       generated by controller, the car will reply with confirmation packed containing this id
     * @param steering -127 = left,     0 = central, 127 = right
     * @param speed    -127 = backward, 0 = neutral, 127 = forward
     */
    public static void send_update(InetSocketAddress to, byte id, byte steering, byte speed) {
        Net.send(to, new byte[]{id, steering, speed});
    }
    public static void send_pong(InetSocketAddress to, byte id) {
        Net.send(to, new byte[]{id});
    }
}
